version: "3"
services:
  mysql:
    image: mysql:5.7.36
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: simple_shop
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./data_mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:10001:3306
    networks:
      - net01
    restart: always
  redis:
    image: redis:6.2.6
    command: --save 60 1 --loglevel warning
    volumes:
      - ./data_redis:/data
    ports:
      - 127.0.0.1:10002:6379
    networks:
      - net01
    restart: always

networks:
  net01:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
